### 识别图片数字
* 图片 28×28 = 784

In [19]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from keras import backend as K
K.clear_session()          # 清除之前会话，防止jupyter缓存影响

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)   # 加载数据（若无则从网上下载，如有则加载本地）

def add_layer(inputs, in_size, out_size, activation_function=None):
    '''添加神经网络层'''
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)
    Wx_plus_b = tf.matmul(inputs, Weights) + biases
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs

def compute_accuracy(v_xs, v_ys):
    global prediction
    y_pre = sess.run(prediction, feed_dict={xs:v_xs})
    correct_prediction = tf.equal(tf.argmax(y_pre, 1), tf.argmax(v_ys, 1))   # 对比真实值最大值的位置与预测值最大值的位置是否相同，1表示行
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    result = sess.run(accuracy, feed_dict={xs:v_xs, ys:v_ys})
    return result

# 传入值
xs = tf.placeholder(tf.float32, [None, 784]) # 28×28
ys = tf.placeholder(tf.float32, [None, 10])  # 数字 0~9

# 输出层
prediction = add_layer(xs, 784, 10, activation_function=tf.nn.softmax)  # softmax 用于分类

# 损失函数
cross_entropy = tf.reduce_mean(-tf.reduce_sum(ys*tf.log(prediction), reduction_indices=[1]))

# 训练优化器
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)    

sess = tf.Session()
sess.run(tf.initialize_all_variables())

for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)    # 从整体数据中取出100个（不采用整体学习的方式，提高学习速度）
    sess.run(train_step, feed_dict={xs:batch_xs, ys:batch_ys})
    if i%50 == 0:
        print('准确率：', compute_accuracy(mnist.test.images, mnist.test.labels))  

Extracting MNIST_data\train-images-idx3-ubyte.gz
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz


W0823 20:50:30.053497  5944 deprecation.py:323] From E:\wk\anaconda3\lib\site-packages\tensorflow\python\util\tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.


准确率： 0.1561
准确率： 0.6486
准确率： 0.7486
准确率： 0.7892
准确率： 0.8086
准确率： 0.8254
准确率： 0.8368
准确率： 0.8402
准确率： 0.8487
准确率： 0.8502
准确率： 0.8599
准确率： 0.8592
准确率： 0.8604
准确率： 0.866
准确率： 0.8677
准确率： 0.8685
准确率： 0.872
准确率： 0.87
准确率： 0.8685
准确率： 0.8761


### reduction_indices
* 指定维度
* 二维数据中，0则为列运算，1则为行运算

In [11]:
import tensorflow as tf
import numpy as np

x = np.array([[1, 2, 3], 
              [4, 5, 6]])

res = tf.reduce_sum(x, reduction_indices=[0])

sess = tf.Session()
print(sess.run(res))

[5 7 9]


In [12]:
res = tf.reduce_sum(x, reduction_indices=[1])

sess = tf.Session()
print(sess.run(res))

[ 6 15]


### tf.argmax()
* 参数为0时，结果为列最大值的索引
* 参数为1时，结果为行最大值的索引
* 以numpy.argmax()示例如下

In [5]:
import numpy as np

test = np.array([[1, 2, 3], 
                 [2, 3, 4], 
                 [5, 4, 3], 
                 [8, 7, 2]])
np.argmax(test, 0)

array([3, 3, 1], dtype=int64)

In [7]:
np.argmax(test, 1)

array([2, 2, 0, 0], dtype=int64)

### tf.cast()
* 数据类型转换
* tf.cast(x, dtype, name=None)