### 预测直线 $y = 0.1x+0.3$

In [18]:
import tensorflow as tf
import numpy as np

'''cread data'''
x_data = np.random.rand(100).astype(np.float32)  # 生成100个随机数，定义为float32类型（TensorFlow中大部分数据类型为float32）
y_data = x_data*0.1 + 0.3  # 直线 y = 0.1x+0.3

'''creat tensorflow structure start'''
Weights = tf.Variable(tf.random_uniform([1], -1.0, 1.0))  # 生成随机数给权重变量，1维，与x_data维数对应，范围-1.0到1.0
biases = tf.Variable(tf.zeros([1]))   # 生成0数组给偏置变量

y = Weights*x_data+biases   # 预测y

loss = tf.reduce_mean(tf.square(y-y_data))          # 损失函数
optimizer = tf.train.GradientDescentOptimizer(0.5)  # 优化器，0.5学习率
train = optimizer.minimize(loss)

init = tf.initialize_all_variables()    # 初始化变量
'''creat tensorflow structure end'''

sess =  tf.Session()
sess.run(init)       # 激活

for step in range(201):
    sess.run(train)
    if step%20 == 0:             # 每隔20步输出权重和偏置值
        print(step, sess.run(Weights), sess.run(biases))

W0822 09:25:28.342821 14580 deprecation.py:323] From E:\wk\anaconda3\lib\site-packages\tensorflow\python\util\tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.


0 [0.00268188] [0.47856715]
20 [0.05835615] [0.321913]
40 [0.08842332] [0.30609167]
60 [0.09678177] [0.30169344]
80 [0.09910537] [0.30047077]
100 [0.09975131] [0.30013087]
120 [0.09993088] [0.3000364]
140 [0.09998079] [0.30001011]
160 [0.09999468] [0.3000028]
180 [0.09999851] [0.3000008]
200 [0.09999958] [0.30000025]


### numpy.random.rand()
* 均匀分布
* 范围[0, 1)

In [5]:
import numpy as np

np.random.rand(3)

array([0.80545471, 0.8132838 , 0.59762584])

In [7]:
np.random.rand(2, 3)

array([[0.79955294, 0.56241534, 0.67593124],
       [0.16356763, 0.71001303, 0.52741388]])

In [8]:
np.random.rand(2, 3, 4)

array([[[0.17844452, 0.36553281, 0.90357176, 0.78932622],
        [0.53421229, 0.13978213, 0.31328913, 0.75269785],
        [0.74034518, 0.87650927, 0.56942711, 0.32820665]],

       [[0.65900708, 0.00297576, 0.65815682, 0.10758077],
        [0.23924928, 0.5804052 , 0.05882578, 0.64222382],
        [0.07063111, 0.28341836, 0.62166267, 0.48983062]]])

### numpy.random.randn()
* 标准正态分布 

In [10]:
np.random.randn(3)

array([0.35738398, 0.02672184, 0.26278804])

In [11]:
np.random.randn(2, 3)

array([[ 0.93106417, -0.38827155, -0.81768464],
       [ 0.46475948, -0.27193259, -0.26922956]])

In [12]:
np.random.randn(2, 3, 4)

array([[[ 0.19908743, -0.92495647,  0.9808552 , -0.47325937],
        [ 1.54989882, -0.06039804, -2.31621729, -0.88064188],
        [-1.74904243, -0.78667573,  0.5063645 , -1.07743022]],

       [[ 0.61918609,  0.64494507, -1.64160336, -0.00268071],
        [ 0.84450151,  0.24076325, -0.78033099,  1.47562072],
        [-0.21921513, -1.0934552 , -0.79426854, -0.5698212 ]]])